cartesian_velocity_node_controller:
    type: franka_control_wrappers/CartesianVelocityNodeController
    arm_id: panda
    # If no new velocity commands are received in time (seconds)
    # Then set 0 velocity.
    max_duration_between_commands: 0.025
    rate_limiting:
        linear:
            velocity: 0.5
            acceleration: 8.0
            jerk: 1000.0
        angular:
            velocity: 0.5
            acceleration: 5.0
            jerk: 2000.0
    stop_on_contact: true

joint_velocity_node_controller:
    type: franka_control_wrappers/JointVelocityNodeController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7